### ISSUE TITLE
Add "Read More" Button to Expand NFT Description

### ISSUE THREAD

**Issue by bhupendra-chouhan** [Rise-In/NFT-Minter#11]
# Tasks: 
- [ ] Add a "Read More" button at the end of the NFT description.
- [ ] Implement an on-click handler that:
 - - [ ] Expands the full NFT description and changes the button text to "Read Less."
 - - [ ] Toggles back to the shortened description on another click, with the button text reverting to "Read More."
- [ ] Ensure the minimum description length is 120 characters before showing the "Read More" button.

**Comment by anandanshul** [comment]
hey @bhupendra-chouhan , please assign me this issue. i can contribute

**Comment by bhupendra-chouhan** [comment]
You have been assigned this issue.
Please make sure to explain your approach to the solution and the changes you made in your PR.
All the best! @anandanshul .

**Comment by bhupendra-chouhan** [comment]
Hey @anandanshul .
If you want to keep yourself updated with latest Web3/Blockchain and opensource related stuff, then make sure to join our TG community and meet more like-minded devs.
Rise In India (TG Link) : https://t.me/risein_india
