### ISSUE TITLE
Add "Search Bar" to Filter NFTs by Creator's GitHub ID

### ISSUE THREAD

**Issue by bhupendra-chouhan** [Rise-In/NFT-Minter#12]
## Description  
Create a "NFT Search Bar" component to allow users to search for all NFTs created by a specific user using their GitHub ID.

## Tasks:
- [x] In `NftList.js` (path: `./src/components/Body/NftList/NftList.js`), declare an array state variable called `filteredNftList` and a setter function `_setFilteredNftList` to track the filtered NFTs.

- [x] Create a component named `NftSearchBar.js` (path: `./src/components/Body/NftList/NftSearchBar.js`) with the following features:
  - [x] Add an input field for users to enter a GitHub ID.
  - [x] Add a "Search" button with an on-click handler that filters items from the `nftList` array and updates `filteredNftList` with the results.

- [x] Import `NftSearchBar.js` into `NftList.js` and position it at the top-center above the NFT cards.
- [x] Render `NftCard.js` for each item in the `filteredNftList` array.

**Comment by saidarshan27** [comment]
Hi, Please assign me this issue. I can contribute @bhupendra-chouhan

**Comment by bhupendra-chouhan** [comment]
You have been assigned this issue. All the best! @saidarshan27

**Comment by saidarshan27** [comment]
sure, thank you

**Comment by saidarshan27** [comment]
what values should I be inserting in for the empty env variables ? @bhupendra-chouhan

**Comment by saidarshan27** [comment]
Hi @bhupendra-chouhan,
I do not have any NFTs nor am I familiar with web3. 
So it would be really helpful if I can get a schema of how the objects in nftList would look like.
Will it be same as mentioned in this picture under updated json metadata? 

![image](https://github.com/user-attachments/assets/aed15059-0a37-4d38-824d-de8fe1071a53)

**Comment by saidarshan27** [comment]
@bhupendra-chouhan 
@SahityaRoy 
@neutr0n420 

Shall we connect through discord or a meet?
I have wanted some clarifications before I proceed with the issue.

**Comment by saidarshan27** [comment]
I have submitted a pull request. Please check

**Comment by bhupendra-chouhan** [comment]
👏 Awesome work @saidarshan27 . Your PR has been successfully merged.
