### ISSUE TITLE
Add a 'Download Metadata' Button

### ISSUE THREAD

**Issue by bhupendra-chouhan** [Rise-In/NFT-Minter#14]
# Tasks:

- [x] Add a 'Download JSON' button to the right of the 'Copy to Clipboard' button inside the `Metadatajson.js` component (path: `src/components/Body/CreateNft/MetadataJson.js`).
- [x] Attach an on-click handler to the download button that:
  - [x] Creates a `.json` file with a filename based on the Unix timestamp when the user clicks the 'Download JSON' button (e.g., `1697743200.json`).
  - [x] Places the NFT metadata's JSON object inside the `.json` file and initiates the download.

**Comment by bhupendra-chouhan** [comment]
Since this has been resolved by @devkumar2313 , I'm closing it.
